// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2b80c972-cd3b-47ec-937f-699f7c65a853";

const char SSID[]               = "Wack House";    // Network SSID (name)
const char PASS[]               = "justice69";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "LDo?lCMab4?mH5sTv92Nk7@Cl";    // Secret device password


float temperature;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
